### ISSUE TITLE
Users can search for results by city

### ISSUE THREAD

**Issue by JanelleGatmaitan** [JanelleGatmaitan/ajax-project#1]
## 💰 Motivation

People who enjoy watching sunsets and sunrises want to know the places with the best views.

## Functionality
When the user types into the search bar and submits their city and state, information from the astronomy and places APIs are stored.

## 📐 Plan

Create a search bar that returns results dependent on user input

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/68579034/108890585-9d69e480-75c2-11eb-9b8a-357c171f3b0c.png)

## ✅ Task List

- [x] Create navbar
- [x] Create search bar with input type
- [x] Submit/search button
- [x] Create card for astronomy search result
- [x] Create card for search results
- [x] Make sure the page looks good on mobile and desktop
- [x] Make a data model to keep track of display, user input, search results, and favorites
- [x] Split the user input to separate between city and state
- [x] Manipulate user input for use in http requests
- [x] Listen for ‘click’ events on the search button and:
  - [x] change class names to hidden
  - [x] update the data model
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality.
- [x] Fix all errors.
