### ISSUE TITLE
Users can view sunrise and sunset times

### ISSUE THREAD

**Issue by JanelleGatmaitan** [JanelleGatmaitan/ajax-project#2]
## 💰 Motivation

Users will want to see search results.

## 📐 Plan

Use JavaScript to respond to user interactions and dynamically update the DOM.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/68579034/108892268-862bf680-75c4-11eb-89dd-56f2b1c3627a.png)

## ✅ Task List

- [x]  Define a function that takes the astroData and displays it for the user to see.
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Reset local storage search results when the user is not on search results page.
- [x] Test all functionality.
- [ ] Fix all errors.
