### ISSUE TITLE
Users can view list of suggested places to watch sunset/sunrise

### ISSUE THREAD

**Issue by JanelleGatmaitan** [JanelleGatmaitan/ajax-project#3]
## 💰 Motivation

Users want to see recommendations for where to watch sunrise and sunset,

## 📐 Plan

Use JavaScript to respond to user interactions and dynamically update the DOM.
Use XMLHttpRequest to send requests to one or more public HTTP APIs.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/68579034/108892144-65fc3780-75c4-11eb-9e77-a8ccc2581046.png)

## ✅ Task List

- [x] Define a function to create the photo urls.
-  [x]  Define a function that takes a single search result object and returns a DOM tree.
- [x] Use a loop to create a DOM tree for each search result in the data model and append it to the page
- [x] Populate search results
- [x] Ensure the page looks the same after page refresh.
- [x] Define a function to reset search results list.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality.
- [x] Fix all errors.
