### ISSUE TITLE
Users can add/delete places to favorites from search page

### ISSUE THREAD

**Issue by JanelleGatmaitan** [JanelleGatmaitan/ajax-project#4]
## 💰 Motivation

Users will want to keep track of their favorite places.

## 📐 Plan

Use JavaScript to respond to user interactions and dynamically update the DOM.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/68579034/108892527-d4d99080-75c4-11eb-898f-8c1975f483ad.png)

## ✅ Task List

- [x] Give each search result an id number attribute.
- [x] Use event delegation.
- [x] Add event listener to search results' parent div. 
- [x] Change like button's class to indicate that it has been favorited.
- [x] store favorited result in localStorage.
- [x] Prevent same result from being favorited multiple times.
- [x] View swap to display favorites when nav bar heart is clicked.
- [x] Manipulate DOM to display favorites
- [x] Ensure page looks the same after refresh
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality.
- [x] Fix all errors.
