### ISSUE TITLE
Users can add delete favorites

### ISSUE THREAD

**Issue by JanelleGatmaitan** [JanelleGatmaitan/ajax-project#5]
## 💰 Motivation

Users will want to remove places from favorites.

## 📐 Plan

Use JavaScript to respond to user interactions and dynamically update the DOM.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/68579034/108892527-d4d99080-75c4-11eb-898f-8c1975f483ad.png)

## ✅ Task List

- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality.
- [ ] Fix all errors.
